### ISSUE TITLE
Add link to theme collection post #1

### ISSUE THREAD

**Issue by eduferfer** [Ademking/awesome-kor#2]
A new post has been published on Medium & dev.to regarding pre-made themes:

- https://dev.to/eduferfer/kor-ui-themes-1-twitch-github-spotify-2i8e
- https://uxplanet.org/kor-ui-themes-1-twitch-github-spotify-4935bc807d16

**Comment by Ademking** [comment]
Thank you @eduferfer so much. I'll add them to the list
